name: Wakatime

on:
  schedule:
    - cron: '30 15 * * *'
  workflow_dispatch:

jobs:
  update-wakatime:
    name: Wakatime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROFILE_VIEWS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_PROJECTS: "False"
          SHOW_COMMIT: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
