name: Wakatime

on:
  schedule:
    - cron: '30 15 * * *'
  workflow_dispatch:

jobs:
  update-wakatime:
    name: Wakatime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LANG_COUNT: 10
          SHOW_TITLE: true
          SHOW_MASKED_TIME: true
          COMMIT_MESSAGE: Update Wakatime Stats
          COMMITTER_NAME: GitHubActionBot
          COMMITTER_EMAIL: action-bot@github.org

      # - uses: anmol098/waka-readme-stats@master
      #   with:
      #     WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      #     GH_TOKEN: ${{ secrets.GH_TOKEN }}
      #     SHOW_PROFILE_VIEWS: "False"
      #     SHOW_SHORT_INFO: "False"
      #     SHOW_LOC_CHART: "False"
      #     SHOW_PROJECTS: "False"
      #     SHOW_COMMIT: "False"
      #     SHOW_LANGUAGE_PER_REPO: "False"
